[workflows."Start application"]
name = "Start application"
command = "bash -lc 'INTERNAL_SECRET=${INTERNAL_SECRET:-dev-secret} BAILEYS_PORT=3300 FLASK_BASE_URL=http://127.0.0.1:5000 BAILEYS_BASE_URL=http://127.0.0.1:3300 ./start_system_stable.sh'"
type = "server"